DROP TABLE IF EXISTS "DOCTORS";
CREATE TABLE DOCTORS(doctor_id INT, doctor_name VARCHAR(20), degree VARCHAR(10));
INSERT INTO "DOCTORS" VALUES(210, "Dr. John Linga", "MD");
INSERT INTO "DOCTORS" VALUES(211, "Dr. Peter Hall", "MBBS");
INSERT INTO "DOCTORS" VALUES(212, "Dr. Ke Gee", "MD");
INSERT INTO "DOCTORS" VALUES(213, "Dr. Pat Fay", "MD");
