DROP TABLE IF EXISTS "SPECIALITY";
CREATE TABLE SPECIALITY(spl_id INT, spl_descrip VARCHAR(10), doctor_id INT);
INSERT INTO "SPECIALITY" VALUES(1, "CARDIO", 211);
INSERT INTO "SPECIALITY" VALUES(2, "NEURO", 213);
INSERT INTO "SPECIALITY" VALUES(3, "ARTHO", 212);
INSERT INTO "SPECIALITY" VALUES(4, "GYNO", 210);
